Evolution-X-Devices/official_devices

builds/j53gxx.json, builds/j5lte.json, builds/j5ltechn.json, builds/j5nlte.json, devices.json
Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>
=> Devices: Add j53gxx, j5lte, j5nlte and j5ltechn

builds/hlte.json, builds/hltechn.json, builds/hltekor.json, builds/hltetmo.json, changelogs/hlte/EvolutionX_hlte-9.0-20190715-2321-OFFICIAL.zip.txt, changelogs/hltechn/EvolutionX_hltechn-9.0-20190716-0847-OFFICIAL.zip.txt, changelogs/hltekor/EvolutionX_hltekor-9.0-20190716-0848-OFFICIAL.zip.txt, changelogs/hltetmo/EvolutionX_hltetmo-9.0-20190716-0938-OFFICIAL.zip.txt, devices.json
* This are Samsung Galaxy note 3 Snapdragon Variants
Signed-off-by: Joshua Primero <jprimero155@gmail.com>
=> Devices: Add HLTE/HLTECHN/HLTEKOR/HLTETMO

builds/sanders.json, changelogs/sanders/EvolutionX_sanders-9.0-20190716-1144-OFFICIAL.zip.txt
Signed-off-by: Mayur (marshmello61/marshmello_61) <ultramayur123@gmail.com>
=> Sanders: 07/16/2019 Update

devices.json
=> platina: fix model name

builds/lavender.json, changelogs/lavender/EvolutionX_lavender-9.0-20190726-0928-OFFICIAL.zip.txt, devices.json
Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>
=> Lavender: 07/26/2019 update

builds/lavender.json
Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>
=> Lavender: Fix maintainer's name

devices.json
Signed-off-by: yashsonawane <yash050219991@gmail.com>
=> Add enchilada

builds/guacamole.json, changelogs/guacamole/EvolutionX_2.0_guacamole-9.0-20190828-1728-OFFICIAL.zip.txt, devices.json
=> Devices: Add Guacamole

devices.json
Signed-off-by: Dusan Uveric <dusan.uveric9@gmail.com>
=> Drop jason support

builds/beryllium.json
Signed-off-by: PainKiller3 <ninadpatil100@gmail.com>
=> Beryllium: 12/17/2019 Update Ota Link

builds/oneplus3.json
=> Update:oneplus3 22/12/2019

builds/sanders.json, changelogs/sanders/EvolutionX_4.0_sanders-10.0-20200108-1422-OFFICIAL.zip.txt, devices.json
* Initial Ten build
Signed-off-by: marshmello61 <ultramayur123@gmail.com>
=> Sanders: 01/08/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.1.69_sanders-10.0-20200311-0750-OFFICIAL.zip.txt
=> Sanders: 03/11/2020 Update

builds/platina.json
Signed-off-by: nysascape <jago@nysascape.digital>
Change-Id: If635175057b9821795ad4fd48cb46571429af6a7
=> Platina: 03/15/2020 update

builds/platina.json, changelogs/platina/EvolutionX_4.1.69_platina-10.0-20200328-0121-OFFICIAL.zip
Change-Id: Icfb7aec27fbe9fe72d1dafa61c9904f80c9ea526
Signed-off-by: nysascape <jago@nysascape.digital>
=> platina: 03/28/20 update

builds/platina.json, changelogs/platina/EvolutionX_4.1.69_platina-10.0-20200328-1611-OFFICIAL.zip.txt
* Fixes bugs from 1st OTA
Change-Id: I82645346a9bec58c6c247d6f759117ad4ab0c55d
Signed-off-by: nysascape <jago@nysascape.digital>
=> Platina: 03/28/20 Update 2

builds/sanders.json, changelogs/sanders/EvolutionX_4.1.69_sanders-10.0-20200329-0531-OFFICIAL.zip.txt
=> sanders: 03/29/2020 update

builds/sanders.json, changelogs/sanders/EvolutionX_4.1.69_sanders-10.0-20200330-0209-OFFICIAL.zip.txt
=> Sanders: 03/30/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.20_sanders-10.0-20200414-0206-OFFICIAL.zip.txt
=> Sanders: 04/14/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.20.1_sanders-10.0-20200417-0821-OFFICIAL.zip.txt
=> Sanders: 04/17/2020 Update

builds/dipper.json, changelogs/dipper/EvolutionX_4.20.1_dipper-10.0-20200419-0950-OFFICIAL.zip.txt
=> Dipper: 04/19/2020 Update

builds/zerofltexx.json, changelogs/zerofltexx/EvolutionX_4.20.1_zerofltexx-10.0-20200419-2302-OFFICIAL.zip.txt, changelogs/zeroltexx/EvolutionX_4.20.1_zeroltexx-10.0-20200420-0051-OFFICIAL.zip.txt
=> Zerofltexx/Zeroltexx: 04/20/2020 Updates

builds/gtaxlwifi.json, changelogs/gtaxlwifi/EvolutionX_4.20.2_gtaxlwifi-10.0-20200425-1224-OFFICIAL.zip.txt
This build fixes the issues on the initial release
=> SATAN: 04/25/2020 Update

builds/dipper.json, changelogs/dipper/EvolutionX_4.20.2_dipper-10.0-20200426-1522-OFFICIAL.zip.txt
=> Dipper: 04/26/2020 Update

builds/Z01R.json, changelogs/Z01R/EvolutionX_4.20.2_Z01R-10.0-20200430-1427-OFFICIAL.zip.txt
=> Z01R: 04/30/2020 Update

builds/taimen.json, changelogs/taimen/EvolutionX_4.1.69_taimen-10.0-20200403-0255-OFFICIAL.zip.txt, changelogs/taimen/EvolutionX_4.20.2_taimen-10.0-20200430-1639-OFFICIAL.zip.txt
=> taimen: 04/30/2020 update

builds/dipper.json, changelogs/dipper/EvolutionX_4.20.2_dipper-10.0-20200501-1324-OFFICIAL.zip.txt
=> Dipper: 05/01/2020 Update

builds/taimen.json, changelogs/taimen/EvolutionX_4.20.2_taimen-10.0-20200430-1639-OFFICIAL.zip.txt, changelogs/taimen/EvolutionX_4.3_taimen-10.0-20200505-1712-OFFICIAL.zip.txt
=> taimen: 05/05/2020 update

builds/platina.json, changelogs/platina/EvolutionX_4.3_platina-10.0-20200507-1505-OFFICIAL.zip.txt
=> Platina: 05/07/2020 1505 update

builds/sanders.json, changelogs/sanders/EvolutionX_4.3_sanders-10.0-20200510-1703-OFFICIAL.zip.txt
=> Sanders: 05/11/2020 Update

builds/zerofltexx.json, builds/zeroltexx.json, changelogs/zerofltexx/EvolutionX_4.3_zerofltexx-10.0-20200511-1751-OFFICIAL.zip.txt, changelogs/zeroltexx/EvolutionX_4.3_zeroltexx-10.0-20200511-1933-OFFICIAL.zip.txt
=> Zerofltexx/Zeroltexx: Update 05/11/2020

builds/taimen.json, changelogs/taimen/EvolutionX_4.3_taimen-10.0-20200524-0241-OFFICIAL.zip.txt
=> Taimen: Update 05/24/2020

devices.json
=> Devices: Drop taimen

builds/polaris.json, changelogs/polaris/EvolutionX_4.4_polaris-10.0-20200604-0150-OFFICIAL.zip.txt
=> Polaris: 06/04/2020 Update

builds/platina.json, changelogs/platina/EvolutionX_4.4_platina-10.0-20200605-2204-OFFICIAL.zip.txt
=> Platina: 06/05/2020 update

builds/taimen.json, changelogs/taimen/EvolutionX_4.4_taimen-10.0-20200605-2323-OFFICIAL.zip.txt
=> Taimen: 06/05/2020 update

builds/sanders.json, changelogs/sanders/EvolutionX_4.4_sanders-10.0-20200608-1029-OFFICIAL.zip.txt
=> Sanders: 06/08/2020 Update

builds/whyred.json, changelogs/whyred/EvolutionX_4.4_whyred-10.0-20200609-2154-OFFICIAL.zip.txt
Signed-off-by: HeartStealer786 <beingme639@gmail.com>
=> Whyred: 06/10/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.4_phoenix-10.0-20200610-0628-OFFICIAL.zip.txt
=> Phoenix: 06/10/2020 Update

builds/dipper.json, changelogs/dipper/EvolutionX_4.4_dipper-10.0-20200612-1404-OFFICIAL.zip.txt
=> Dipper: 06/12/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.4_phoenix-10.0-20200614-1549-OFFICIAL.zip.txt
=> Phoenix: 06/14/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.4_pyxis-10.0-20200617-0527-OFFICIAL.zip.txt
=> Pyxis: 06/17/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.4_polaris-10.0-20200617-2127-OFFICIAL.zip.txt
=> Polaris: 06/17/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.4_phoenix-10.0-20200623-1718-OFFICIAL.zip.txt
=> Phoenix: 06/23/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.4_pyxis-10.0-20200628-1956-OFFICIAL.zip.txt
=> Pyxis: 06/28/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.4_polaris-10.0-20200628-1334-OFFICIAL.zip.txt
=> Polaris: 06/28/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.5_pyxis-10.0-20200707-1223-OFFICIAL.zip.txt
=> Pyxis: 07/07/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.5_polaris-10.0-20200708-1421-OFFICIAL.zip.txt
=> Polaris: 07/08/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.5_pyxis-10.0-20200709-1217-OFFICIAL.zip.txt
=> Pyxis: 07/09/2020

builds/x2.json, changelogs/x2/EvolutionX_4.5_x2-10.0-20200710-0842-OFFICIAL.zip.txt
=> x2: 07/10/2020 Update

builds/x2.json, changelogs/x2/EvolutionX_4.5_x2-10.0-20200711-1308-OFFICIAL.zip.txt
=> x2: 07/11/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.5_polaris-10.0-20200713-0131-OFFICIAL.zip.txt
=> Polaris: 07/13/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.5_sanders-10.0-20200714-0429-OFFICIAL.zip.txt
=> Sanders: 07/14/2020 Update

builds/vince.json, changelogs/vince/EvolutionX_4.5_vince-10.0-20200714-0943-OFFICIAL.zip.txt
Signed-off-by: IAmSalvaMartini <starraos@gmail.com>
=> Vince: 07/14/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.5_polaris-10.0-20200718-1921-OFFICIAL.zip.txt
=> Polaris: 07/18/2020 Update

builds/x2.json, changelogs/x2/EvolutionX_4.5_x2-10.0-20200721-1236-OFFICIAL.zip.txt
=> x2: 07/21/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.5_phoenix-10.0-20200723-1256-OFFICIAL.zip.txt
=> Phoenix: 07/23/2020 Update

builds/dipper.json, changelogs/dipper/EvolutionX_4.5_dipper-10.0-20200724-1631-OFFICIAL.zip.txt
=> Dipper: 07/24/2020 Update

builds/x2.json, changelogs/x2/EvolutionX_4.5_x2-10.0-20200727-0206-OFFICIAL.zip.txt
=> x2: 07/27/2020 Update

devices.json
Signed-off-by: IAmSalvaMartini <starraos@gmail.com>
=> Drop Redmi 5 Plus Global(Vince)

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.6_phoenix-10.0-20200804-1239-OFFICIAL.zip.txt
=> Phoenix: 08/04/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.6_polaris-10.0-20200804-0732-OFFICIAL.zip.txt
=> Polaris: 08/04/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.6_phoenix-10.0-20200809-0627-OFFICIAL.zip.txt
=> Phoenix: 08/09/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.6_sanders-10.0-20200810-0503-OFFICIAL.zip.txt
=> Sanders: 08/10/2020 Update

builds/taimen.json, changelogs/taimen/EvolutionX_4.6_taimen-10.0-20200812-0300-OFFICIAL.zip.txt
=> taimen: 08/12/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.6_pyxis-10.0-20200818-0408-OFFICIAL.zip.txt
=> Pyxis: 08/18/2020 Update

builds/ginkgo.json, changelogs/ginkgo/EvolutionX_4.6_ginkgo-10.0-20200819-0341-OFFICIAL.zip.txt
Signed-off-by: Rodrigo Martinez <rear097@gmail.com>
=> Ginkgo: 08/19/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_4.6_phoenix-10.0-20200827-0918-OFFICIAL.zip.txt
=> Phoenix: 08/27/2020 Update

builds/guacamole.json, changelogs/guacamole/EvolutionX_4.6_guacamole-10.0-20200827-0345-OFFICIAL.zip.txt
Signed-off-by: Justin Crawford <Justin@Stacksmash.net>
=> guacamole: 08/27/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.6_polaris-10.0-20200903-1428-OFFICIAL.zip.txt
=> Polaris: 09/03/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.7_sanders-10.0-20200910-1240-OFFICIAL.zip.txt
=> Sanders: 09/11/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.7_pyxis-10.0-20200913-1156-OFFICIAL.zip.txt
=> Pyxis: 09/13/2020 Update

builds/sanders.json, changelogs/sanders/EvolutionX_4.7_sanders-10.0-20200913-1458-OFFICIAL.zip.txt
=> Sanders: 09/14/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.7_pyxis-10.0-20200915-1521-OFFICIAL.zip.txt
=> Pyxis: 09/15/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.7_polaris-10.0-20200918-0746-OFFICIAL.zip.txt
=> Polaris: 09/18/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.7_pyxis-10.0-20200922-2106-OFFICIAL.zip.txt
=> Pyxis: 09/22/2020 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_4.7_pyxis-10.0-20200924-2032-OFFICIAL.zip.txt
=> Pyxis: 09/24/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_4.7_polaris-10.0-20200925-2037-OFFICIAL.zip.txt
=> Polaris: 09/25/2020 Update

builds/RMX1971.json, changelogs/RMX1971/EvolutionX_4.7_RMX1971-10.0-20200911-0556-OFFICIAL.zip.txt, devices.json
=> Devices: Add RMX1971

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_4.7_RMX206X-10.0-20201004-0730-OFFICIAL.zip.txt, devices.json
=> Devices: Add Realme 6 Pro

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_4.7_RMX206X-10.0-20201020-0237-OFFICIAL.zip.txt
=> RMX206X: 10/20/2020 Update

builds/sakura.json, changelogs/sakura/EvolutionX_5.1_sakura-11-20201112-0926-OFFICIAL.zip.txt
Signed-off-by: ZèD <imzihad@gmail.com>
=> sakura: 11/12/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.1_polaris-11-20201119-0528-OFFICIAL.zip.txt
=> Polaris: 11/19/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.1_polaris-11-20201120-1015-OFFICIAL.zip.txt
=> Polaris: 11/20/2020 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.1_phoenix-11-20201122-1823-OFFICIAL.zip.txt, devices.json
=> Devices: Add Xiaomi Redmi K30 / POCO X2 to Official

builds/fajita.json, changelogs/fajita/EvolutionX_5.1_fajita-11-20201128-1052-OFFICIAL.zip.txt
=> Fajita: 11/28/2020 Update

builds/X00QD.json, changelogs/X00QD/EvolutionX_5.2_X00QD-11-20201211-2353-OFFICIAL.zip.txt
Signed-off-by: emincangencer <emincange@gmail.com>
=> X00QD: 12/11/2020 Update

builds/whyred.json, changelogs/whyred/EvolutionX_5.2_whyred-11-20201215-1559-OFFICIAL.zip.txt
Signed-off-by: Zaviyar786 <beingme639@gmail.com>
=> Whyred: 12/15/2020 Update

builds/X00TD.json, changelogs/X00TD/EvolutionX_5.2_X00TD-11-20201220-0502-OFFICIAL.zip.txt
Change-Id: I5b8db249332a782825c2053171b596b10fcbc789
=> X00TD: 12/20/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.2_polaris-11-20201228-0914-OFFICIAL.zip.txt
=> Polaris: 12/28/2020 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.3_polaris-11-20210105-1618-OFFICIAL.zip.txt
=> Polaris: 01/05/2021 Update

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_5.3_RMX206X-11-20210107-0845-OFFICIAL.zip.txt
=> RMX206X: 01/07/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.3_dipper-11-20210108-0940-OFFICIAL.zip.txt
=> Dipper: 01/08/2021 Update

builds/X00QD.json, changelogs/X00QD/EvolutionX_5.3_X00QD-11-20210108-1249-OFFICIAL.zip.txt, devices.json
Signed-off-by: emincangencer <emincange@gmail.com>
=> X00QD: 01/08/2021 update

builds/guacamole.json, changelogs/guacamole/EvolutionX_5.3_guacamole-11-20210108-1316-OFFICIAL.zip.txt
Signed-off-by: Justin Crawford <Justin@stacksmash.net>
=> Guacamole: 01/08/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.3_polaris-11-20210114-0015-OFFICIAL.zip.txt
=> Polaris: 01/14/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.3_dipper-11-20210114-0804-OFFICIAL.zip.txt
=> Dipper: 01/14/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.3_enchilada-11-20210115-1343-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.3_fajita-11-20210115-1154-OFFICIAL.zip.txt
=> Enchilada/Fajita: 01/15/2021 Update

builds/surya.json, changelogs/surya/EvolutionX_5.3_surya-11-20210115-1316-OFFICIAL.zip.txt, devices.json
Signed-off-by: IAmSalvaMartini <starraos@gmail.com>
=> Devices: Add Poco X3 (surya)

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_5.3_RMX206X-11-20210116-0629-OFFICIAL.zip.txt, devices.json
=> RMX206X: 01/16/2021 Update

builds/whyred.json, changelogs/whyred/EvolutionX_5.3_whyred-11-20210117-0649-OFFICIAL.zip.txt
Signed-off-by: Zaviyar786 <beingme639@gmail.com>
=> Whyred: 01/17/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.3_dipper-11-20210117-1245-OFFICIAL.zip.txt
=> Dipper: 01/17/2021 Update

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_5.3_RMX206X-11-20210118-0952-OFFICIAL.zip.txt
=> RMX206X: 01/18/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.3_dipper-11-20210121-1612-OFFICIAL.zip.txt
=> Dipper: 01/21/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.3_polaris-11-20210123-0312-OFFICIAL.zip.txt
=> Polaris: 01/23/2021 Update

builds/Z01R.json, changelogs/Z01R/EvolutionX_5.3_Z01R-11-20210125-0903-OFFICIAL.zip.txt
Signed-off-by: Aryan Arora <arora.aryan7@gmail.com>
=> Z01R: 01/25/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.3_dipper-11-20210125-1514-OFFICIAL.zip.txt
=> Dipper: 01/25/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.3_polaris-11-20210127-2249-OFFICIAL.zip.txt
=> Polaris: 01/27/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.3_enchilada-11-20210128-0803-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.3_fajita-11-20210128-0559-OFFICIAL.zip.txt
=> Enchilada/Fajita: 01/28/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.3_phoenix-11-20210130-1853-OFFICIAL.zip.txt
Signed-off-by: chiranth <chiranthangadi123@gmail.com>
=> Phoenix: 01/31/2021 Update

builds/fajita.json, changelogs/fajita/EvolutionX_5.4_fajita-11-20210202-0939-OFFICIAL.zip.txt
=> Fajita: 02/02/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.4_dipper-11-20210202-1341-OFFICIAL.zip.txt
=> Dipper: 02/02/2021 Update

builds/enchilada.json, changelogs/enchilada/EvolutionX_5.4_enchilada-11-20210202-1447-OFFICIAL.zip.txt
=> Enchilada: 02/02/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.4_violet-11-20210202-1054-OFFICIAL.zip.txt
=> violet: 02/02/20201 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.4_dipper-11-20210205-2146-OFFICIAL.zip.txt
=> Dipper: 02/05/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.4_laurel_sprout-11-20210206-0656-OFFICIAL.zip.txt
=> laurel_sprout: 02/06/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.4_dipper-11-20210210-1333-OFFICIAL.zip.txt
=> Dipper: 02/10/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.4_enchilada-11-20210211-0555-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.4_fajita-11-20210211-0434-OFFICIAL.zip.txt
=> Enchilada/Fajita: 02/11/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.4_polaris-11-20210211-1145-OFFICIAL.zip.txt
=> Polaris: 02/11/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.4_dipper-11-20210213-1233-OFFICIAL.zip.txt
=> Dipper: 02/13/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.4_violet-11-20210215-0656-OFFICIAL.zip.txt
=> violet: 02/15/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.4_enchilada-11-20210218-0428-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.4_fajita-11-20210218-0318-OFFICIAL.zip.txt
=> Enchilada/Fajita: 02/18/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.4_laurel_sprout-11-20210219-0913-OFFICIAL.zip.txt
=> Laurel_sprout: 02/19/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.4_dipper-11-20210224-1017-OFFICIAL.zip.txt
=> Dipper: 02/24/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.4_polaris-11-20210228-0619-OFFICIAL.zip.txt
=> Polaris: 02/28/2021 Update

builds/fajita.json, changelogs/fajita/EvolutionX_5.5_fajita-11-20210303-0454-OFFICIAL.zip.txt
=> Fajita: 03/03/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.5_dipper-11-20210303-1525-OFFICIAL.zip.txt
=> Dipper: 03/03/2021 Update

builds/enchilada.json, changelogs/enchilada/EvolutionX_5.5_enchilada-11-20210303-1902-OFFICIAL.zip.txt
=> Enchilada: 03/03/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.5_laurel_sprout-11-20210304-0339-OFFICIAL.zip.txt
=> Laurel_Sprout: 03/04/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.5_enchilada-11-20210306-1124-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.5_fajita-11-20210306-1044-OFFICIAL.zip.txt
=> Enchilada/Fajita: 03/06/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.5_dipper-11-20210306-1030-OFFICIAL.zip.txt
=> Dipper: 03/06/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.5_enchilada-11-20210307-0313-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.5_fajita-11-20210307-0454-OFFICIAL.zip.txt
=> Enchilada/Fajita: 03/07/2021 Update

builds/lake.json, changelogs/lake/EvolutionX_5.5_lake-11-20210316-1538-OFFICIAL.zip.txt, devices.json
=> Devices: Add Motorola G7 Plus to Official

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.5.1_enchilada-11-20210319-1000-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.5.1_fajita-11-20210319-0801-OFFICIAL.zip.txt
=> Enchilada/Fajita: 03/19/2021 Update

builds/fajita.json, changelogs/fajita/EvolutionX_5.5.1_fajita-11-20210320-0856-OFFICIAL.zip.txt
=> Fajita: 03/20/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.5.2_laurel_sprout-11-20210322-0806-OFFICIAL.zip.txt
=> Laurel_Sprout: 03/22/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.5.2_phoenix-11-20210322-0826-OFFICIAL.zip.txt
Signed-off-by: Chiranth <chiranthangadi123@gmail.com>
=> Phoenix: 03/22/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.5.2_polaris-11-20210322-1630-OFFICIAL.zip.txt
=> Polaris: 03/22/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.5.2_laurel_sprout-11-20210324-0638-OFFICIAL.zip.txt
=> Laurel_Sprout: 03/24/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.5.2_violet-11-20210324-0437-OFFICIAL.zip.txt
=> violet: 03/25/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.5.2_phoenix-11-20210326-1857-OFFICIAL.zip.txt
=> Phoenix: 03/27/2021 Update

builds/dipper.json, changelogs/dipper/EvolutionX_5.5.2_dipper-11-20210327-1400-OFFICIAL.zip.txt
=> Dipper: 03/27/2021 Update

builds/instantnoodle.json, builds/instantnoodlep.json, builds/kebab.json, changelogs/instantnoodle/EvolutionX_5.5.2_instantnoodle-11-20210327-1721-OFFICIAL.zip.txt, changelogs/instantnoodlep/EvolutionX_5.5.2_instantnoodlep-11-20210327-1754-OFFICIAL.zip.txt, changelogs/kebab/EvolutionX_5.5.2_kebab-11-20210327-1646-OFFICIAL.zip.txt, devices.json
=> Devices: Add OnePlus 8/Pro/T to official devices

builds/violet.json, changelogs/violet/EvolutionX_5.5.2_violet-11-20210328-1607-OFFICIAL.zip.txt
=> violet: 03/28/2021 Update

builds/RMX206X.json, changelogs/RMX206X/EvolutionX_5.5.2_RMX206X-11-20210329-0545-OFFICIAL.zip.txt
=> RMX206X: 03/29/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.5.2_enchilada-11-20210329-1143-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.5.2_fajita-11-20210329-1106-OFFICIAL.zip.txt
=> Enchilada/Fajita: 03/29/2021 Update

builds/vince.json, changelogs/vince/EvolutionX_5.5.2_vince-11-20210329-2038-OFFICIAL.zip.txt
Signed-off-by: IAmSalvaMartini <starraos@gmail.com>
=> Vince: 03/30/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.5.2_kebab-11-20210327-1646-OFFICIAL.zip.txt, changelogs/kebab/EvolutionX_5.5.2_kebab-11-20210330-1323-OFFICIAL.zip.txt
=> Kebab 03/30/2021 Update

builds/sanders.json, changelogs/sanders/EvolutionX_5.5.2_sanders-11-20210401-0817-OFFICIAL.zip.txt
Signed-off-by: marshmello61 <ultramayur123@gmail.com>
=> Sanders: 04/01/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.5.2_polaris-11-20210404-2205-OFFICIAL.zip.txt
=> Polaris: 04/04/2021 Update

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/EvolutionX_5.6_enchilada-11-20210406-0925-OFFICIAL.zip.txt, changelogs/fajita/EvolutionX_5.6_fajita-11-20210406-0802-OFFICIAL.zip.txt
=> Enchilada/Fajita: 04/06/2021 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_5.6_pyxis-11-20210406-1417-OFFICIAL.zip.txt
=> Pyxis: 04/06/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.6_phoenix-11-20210407-0959-OFFICIAL.zip.txt
=> Phoenix: 04/07/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.6_laurel_sprout-11-20210407-0614-OFFICIAL.zip.txt
=> Laurel_Sprout: 04/07/2021 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_5.6_pyxis-11-20210407-1735-OFFICIAL.zip.txt
=> Pyxis: 04/07/2021 Update

builds/sanders.json, changelogs/sanders/EvolutionX_5.6_sanders-11-20210408-0314-OFFICIAL.zip.txt
Signed-off-by: marshmello61 <ultramayur123@gmail.com>
=> Sanders: 04/08/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.6_laurel_sprout-11-20210408-1701-OFFICIAL.zip.txt
=> Laurel_Sprout: 04/09/2021 Update

builds/pyxis.json, changelogs/pyxis/EvolutionX_5.6_pyxis-11-20210417-1659-OFFICIAL.zip.txt
=> Pyxis: 04/17/2021 Update

builds/whyred.json, changelogs/whyred/EvolutionX_5.6_whyred-11-20210418-0820-OFFICIAL.zip.txt
Signed-off-by: Zaviyar786 <beingme639@gmail.com>
=> Whyred: 04/18/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.6_violet-11-20210421-1036-OFFICIAL.zip.txt
=> violet: 04/21/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.6_phoenix-11-20210422-0747-OFFICIAL.zip.txt
=> Phoenix: 04/22/2021 Update

builds/X00TD.json, changelogs/X00TD/EvolutionX_5.6_X00TD-11-20210422-0513-OFFICIAL.zip.txt
Change-Id: Ib3d1806ced09fd1987bf01a54b1cd76b5d3bb809
=> X00TD: 04/22/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.6.1_polaris-11-20210424-1321-OFFICIAL.zip.txt
=> Polaris: 04/24/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.6.1_kebab-11-20210426-1254-OFFICIAL.zip.txt
=> Kebab: 04/26/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.6.1_phoenix-11-20210427-0738-OFFICIAL.zip.txt
=> Phoenix: 04/27/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.7_kebab-11-20210504-1529-OFFICIAL.zip.txt
=> Kebab: 05/04/2021 Update

builds/X00TD.json, changelogs/X00TD/EvolutionX_5.7_X00TD-11-20210504-1754-OFFICIAL.zip.txt
Change-Id: Ibded1234faa9be07796b9a8ea69a3be8fd4e8a0d
=> X00TD: 05/04/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.7_laurel_sprout-11-20210505-1639-OFFICIAL.zip.txt
=> Laurel_Sprout: 05/05/2021 Update

builds/sanders.json, changelogs/sanders/EvolutionX_5.7_sanders-11-20210505-0913-OFFICIAL.zip.txt
=> Sanders: 05/06/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.7_laurel_sprout-11-20210506-1757-OFFICIAL.zip.txt
=> Laurel_Sprout: 05/06/2021 Update

devices.json
=> Devices: Drop Enchilada & Fajita Device

builds/polaris.json, changelogs/polaris/EvolutionX_5.7_polaris-11-20210508-0030-OFFICIAL.zip.txt
=> Polaris: 05/08/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.7_kebab-11-20210513-0814-OFFICIAL.zip.txt
=> Kebab: 05/13/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.7_phoenix-11-20210514-1431-OFFICIAL.zip.txt
=> Phoenix: 05/14/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.7_violet-11-20210515-0550-OFFICIAL.zip.txt
=> violet: 05/15/2021 Update

xda/features.md
=> XDA: Update features to reflect v5.7

xda/device_groups.md
=> Telegram: Initialize device_groups.md

builds/polaris.json, changelogs/polaris/EvolutionX_5.7_polaris-11-20210519-0450-OFFICIAL.zip.txt
=> Polaris: 05/19/2021 Update

builds/instantnoodle.json, builds/instantnoodlep.json, changelogs/instantnoodle/EvolutionX_5.7_instantnoodle-11-20210519-1741-OFFICIAL.zip.txt, changelogs/instantnoodlep/EvolutionX_5.7_instantnoodlep-11-20210519-1608-OFFICIAL.zip.txt
=> Instantnoodle/Instantnoodlep: 05/19/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.7_kebab-11-20210520-0332-OFFICIAL.zip.txt
=> Kebab: 05/20/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.7_polaris-11-20210524-0028-OFFICIAL.zip.txt
=> Polaris: 05/24/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.7_phoenix-11-20210524-1531-OFFICIAL.zip.txt
=> Phoenix: 05/24/2021 Update

builds/kebab.json, changelogs/kebab/EvolutionX_5.7_kebab-11-20210525-0303-OFFICIAL.zip.txt
=> Kebab: 05/25/2021 Update

builds/instantnoodle.json, builds/instantnoodlep.json, changelogs/instantnoodle/EvolutionX_5.7_instantnoodle-11-20210528-2022-OFFICIAL.zip.txt, changelogs/instantnoodlep/EvolutionX_5.7_instantnoodlep-11-20210528-1914-OFFICIAL.zip.txt
=> Instantnoodle/Instantnoodlep: 05/28/2021 Update

builds/instantnoodle.json, changelogs/instantnoodle/EvolutionX_5.7_instantnoodle-11-20210530-0610-OFFICIAL.zip
=> Instantnoodle: 05/30/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.8_phoenix-11-20210608-0758-OFFICIAL.zip.txt
=> Phoenix: 06/08/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.8_phoenix-11-20210612-0646-OFFICIAL.zip.txt
=> Phoenix: 06/12/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.8_polaris-11-20210613-2203-OFFICIAL.zip.txt
=> Polaris: 06/13/2021 Update

builds/violet.json, changelogs/violet/EvolutionX_5.8_violet-11-20210615-0352-OFFICIAL.zip.txt
=> violet: 06/15/2021 Update

builds/sanders.json, changelogs/sanders/EvolutionX_5.8_sanders-11-20210619-0159-OFFICIAL.zip.txt
=> Sanders: 06/19/2021 Update

builds/X00TD.json, changelogs/X00TD/EvolutionX_5.8_X00TD-11-20210622-1742-OFFICIAL.zip.txt
Change-Id: I24fa4228337e8c97ac6d4ed23648175cb7c19bb2
=> X00TD: 06/23/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.8_polaris-11-20210624-0151-OFFICIAL.zip.txt
=> Polaris: 06/24/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.8_phoenix-11-20210625-0711-OFFICIAL.zip.txt
=> Phoenix: 06/25/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.8_polaris-11-20210627-0234-OFFICIAL.zip.txt
=> Polaris: 06/27/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.8_phoenix-11-20210627-1705-OFFICIAL.zip.txt
=> Phoenix: 06/27/2021 Update

builds/instantnoodle.json, builds/instantnoodlep.json, builds/kebab.json, changelogs/instantnoodle/EvolutionX_5.8_instantnoodle-11-20210702-1857-OFFICIAL.zip.txt, changelogs/instantnoodlep/EvolutionX_5.8_instantnoodlep-11-20210702-1600-OFFICIAL.zip.txt, changelogs/kebab/EvolutionX_5.8_kebab-11-20210702-2113-OFFICIAL.zip.txt
=> Instantnoodle/Instantnoodlep/Kebab: 07/02/2021 Update

builds/phoenix.json, changelogs/phoenix/EvolutionX_5.9_phoenix-11-20210708-0419-OFFICIAL.zip.txt
=> Phoenix: 07/08/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/EvolutionX_5.9_laurel_sprout-11-20210708-0640-OFFICIAL.zip.txt
=> Laurel_Sprout: 07/08/2021 Update

builds/polaris.json, changelogs/polaris/EvolutionX_5.9_polaris-11-20210709-1224-OFFICIAL.zip.txt
=> Polaris: 07/09/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.210705.001-07120827-unsigned.zip.txt
=> Polaris: 07/12/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-rq3a.210705.001-07121337.zip.txt
=> Phoenix: 07/12/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-rq3a.210705.001-07180741.zip.txt, devices.json
=> Devices: Add Xiaomi POCO F3 to official

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.210705.001-07200639-unsigned.zip.txt
=> Polaris: 07/20/2021 Update

builds/violet.json, changelogs/violet/evolution_violet-ota-rq3a.210705.001-07211617.zip.txt
=> violet: 07/21/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-rq3a.210705.001-07250633.zip.txt
=> Phoenix: 07/25/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-rq3a.210805.001.a1-08031114.zip.txt
=> Phoenix: 08/03/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.210805.001.a1-08081935-unsigned.zip.txt
=> Poliars: 08/08/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-rq3a.210805.001.a1-08121707.zip.txt
=> Alioth: 08/12/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-rq3a.210805.001.a1-08140705.zip.txt
=> Laurel_Sprout: 08/16/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-rq3a.210805.001.a1-08160644.zip.txt
=> Alioth: 08/16/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.210805.001.a1-09010753-unsigned.zip.txt
=> Polaris: 09/01/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-rq3a.210905.001-09080840.zip.txt
=> Phoenix: 09/08/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-rq3a.210905.001-09111704.zip.txt
=> Laurel_Sprout: 09/11/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.210905.001-09191152-unsigned.zip.txt
=> Polaris: 09/19/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-rq3a.211001.001-11170302-unsigned.zip.txt
=> Polaris: 11/17/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-rq3a.211001.001-11181520.zip.txt
=> Alioth: 11/19/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-rq3a.211001.001-11222334.zip.txt
=> Alioth: 11/23/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sd1a.210817.036.a8-11241646.zip.txt
=> Phoenix: 11/25/2021 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.211205.016.a1-12171250.zip.txt
=> Phoenix: 12/17/2021 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-sq1d.211205.016.a1-12190754.zip.txt
=> Laurel_Sprout: 12/19/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.211205.016.a1-12241027.zip.txt
=> Alioth: 12/24/2021 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.211205.016.a1-12261652.zip.txt
=> Alioth: 12/26/2021 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sq1d.211205.016.a1-01030957-unsigned.zip.txt
=> Polaris: 01/03/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.211205.016.a1-01091855.zip.txt
=> Phoenix: 01/10/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.220105.007-01151916.zip.txt
=> Alioth: 01/15/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.220105.007-01161037.zip.txt
=> Phoenix: 01/16/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.220105.007-01181758.zip.txt
=> Alioth: 18/01/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.220105.007-01220553.zip.txt
=> Phoenix: 01/22/2022 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-sq1d.220105.007-01211302.zip.txt
=> Laurel_Sprout: 01/21/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sq1d.220105.007-01230545-unsigned.zip.txt
=> Polaris: 01/23/2022 Update

builds/violet.json, changelogs/violet/evolution_violet-ota-sq1d.220105.007-01271407.zip.txt
Signed-off-by: Mir Yasin Ali <miryasin@m.ms.evolution-x.org>
=> violet: 01/27/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.220105.007-01280919.zip.txt
Signed-off-by: chiru2000 <chiranth@m.ms.evolution-x.org>
=> Phoenix: 01/28/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.220205.003-02090612.zip.txt
=> Phoenix: 02/09/2022 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-sq1d.220205.003-02090614.zip.txt
=> Laurel_Sprout: 02/09/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sq1d.220205.003-02130533-unsigned.zip.txt
=> Polaris: 02/13/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.220205.003-02150813.zip.txt
=> Alioth: 02/15/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.220205.004-02190913.zip.txt
=> Alioth: 02/19/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq1d.220205.004-02222024.zip.txt, devices.json
=> Devices: Add Xiaomi Poco X3 Pro [vayu]

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq1d.220205.004-03010523.zip.txt
Change-Id: Ie4449eeb3dd590143b883f621557afe0974aadd8
=> Phoenix: 03/01/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq1d.220205.004-03011644.zip.txt
=> Alioth: 03/01/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sp2a.220305.012-03141950.zip.txt
=> Alioth: 03/14/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220305.012-03200623.zip.txt
=> Vayu: 03/20/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sp2a.220305.013.a3-03291850.zip.txt
=> Alioth: 03/29/2022 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-sp2a.220305.013.a3-04022339.zip.txt
=> Laurel_Sprout: 04/02/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sp2a.220305.013.a3-04030425-unsigned.zip.txt
=> Polaris: 04/04/2022 Update

builds/whyred.json, changelogs/whyred/evolution_whyred-ota-sp2a.220405.004-04071533.zip.txt
=> Whyred: 04/07/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sp2a.220405.004-04081027.zip.txt
Change-Id: Id11f308ece2b676288d1941b181078e7fa5598b3
=> Phoenix: 04/08/2022 Update

builds/mi439.json, changelogs/mi439/evolution_mi439-ota-sp2a.220405.004-04090722-unsigned.zip.txt
=> mi439: 04/09/2022 update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220405.004-04101002.zip.txt
=> Vayu: 04/10/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220405.004-04120347.zip.txt
=> Vayu: 04/12/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sp2a.220405.004-04130848.zip.txt
Signed-off-by: DarkAngelGR01 <asavvo01@gmail.com>
=> Alioth: 04/13/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sp2a.220405.004-04190441.zip.txt
Change-Id: I141f0cfaa78ecddecfe7410ba306aedc4481d8d6
=> Phoenix: 04/19/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220405.004-04230002.zip.txt
=> Vayu: 04/23/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sp2a.220405.004-04240931-unsigned.zip.txt
=> Polaris: 04/24/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220405.004-04250532.zip.txt
=> Vayu: 04/25/2022 Update

builds/RMX2170.json, changelogs/RMX2170/evolution_RMX2170-ota-sp2a.220405.004-04251729-unsigned.zip.txt
=> RMX2170: 04/25/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sp2a.220405.004-04301539.zip.txt
Change-Id: Ic17c327a4bac603d02ce8d9fdfd617b914797d92
=> Phoenix: 04/30/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sp2a.220505.002-05071329-unsigned.zip.txt
=> Polaris: 05/07/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sp2a.220505.002-05141409.zip.txt
=> Alioth: 05/14/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sp2a.220505.002-05140646.zip.txt
Change-Id: I2f313d861b5b1d281b1c0180d5bb82a079831203
=> Phoenix: 05/14/2022 Update

builds/whyred.json, changelogs/whyred/evolution_whyred-ota-sp2a.220505.002-05211456.zip.txt
=> Whyred: 05/22/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sp2a.220505.002-05261642.zip.txt
=> Vayu: 05/26/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sp2a.220505.002-05270635.zip.txt, incremental/builds/phoenix.json, incremental/changelogs/phoenix/evolution_phoenix-delta-sp2a.220505.002-05270635.zip.txt
Change-Id: I9e5553184b41b2cdefc6f733aed395a41f2ad4bc
=> Phoenix: 05/27/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sp2a.220505.002-05311725.zip.txt
=> Alioth: 05/31/2022 Update

builds/surya.json, changelogs/surya/evolution_surya-ota-sq3a.220605.009.b1-06081124-unsigned.zip.txt
Signed-off-by: Lostark13 <tushar9915@gmail.com>
=> surya: 08/06/2022 Update

builds/whyred.json, changelogs/whyred/evolution_whyred-ota-sq3a.220605.009.b1-06091546.zip.txt
=> Whyred: 06/09/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq3a.220605.009.b1-06092144.zip.txt
Change-Id: I0c52ded1412ab2b44a54cb0f16d5b8fb960c9bc2
=> Phoenix: 06/09/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220605.009.b1-06100722.zip.txt
=> Vayu: 06/10/2022 Update

builds/surya.json, changelogs/surya/evolution_surya-ota-sq3a.220605.009.b1-06101046-unsigned.zip.txt
Signed-off-by: Lostark13 <tushar9915@gmail.com>
=> Surya: 06/10/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-sq3a.220605.009.b1-06231340-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-sq3a.220605.009.b1-06231635-unsigned.zip.txt, changelogs/starlte/evolution_starlte-ota-sq3a.220605.009.b1-06231818-unsigned.zip.txt
=> Starlte/Star2lte/Crownlte: 06/24/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220605.009.b1-06250246.zip.txt
=> Alioth: 06/25/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220605.009.b1-06251944.zip.txt
=> Alioth: 06/26/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220605.009.b1-06300857.zip.txt
=> Vayu: 06/30/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-sq3a.220705.003.a1-07070730-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-sq3a.220705.003.a1-07071238-unsigned.zip.txt, changelogs/starlte/evolution_crownlte-ota-sq3a.220705.003.a1-07070730-unsigned.zip.txt
=> Starlte/Star2lte/Crownlte: 07/07/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220705.003.a1-07101003.zip.txt
=> Vayu: 07/10/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-sq3a.220705.003.a1-07111134.zip.txt
Change-Id: Ib3d0cdb12ec46be1e3405c174faa3b3fae411688
=> Phoenix: 07/11/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220705.003.a1-07111422.zip.txt
=> Alioth: 07/11/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220705.003.a1-07151048.zip.txt
=> Alioth: 07/15/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220705.003.a1-07201102.zip.txt
=> Vayu: 07/20/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-sq3a.220705.003.a1-07201738-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-sq3a.220705.003.a1-07210529-unsigned.zip.txt, changelogs/starlte/evolution_starlte-ota-sq3a.220705.003.a1-07210617-unsigned.zip,txt
=> Starlte/Star2lte/Crownlte: 07/21/2022 Update

builds/whyred.json, changelogs/whyred/evolution_whyred-ota-sq3a.220705.003.a1-07281546.zip.txt
=> Whyred: `07/28/2022` Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220705.003.a1-07310338.zip.txt
=> Vayu: 07/31/2022 Update

builds/whyred.json, changelogs/whyred/evolution_whyred-ota-sq3a.220705.004-08090619.zip
=> Whyred: 08/09/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220705.004-08091910.zip.txt
=> Alioth: 08/09/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-sq3a.220705.004-08121434-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-sq3a.220705.004-08121559-unsigned.zip.txt, changelogs/starlte/evolution_starlte-ota-sq3a.220705.004-08121630-unsigned.zip.txt
=> Starlte/Star2lte/Crownlte: 08/12/2022 Update

builds/surya.json, changelogs/surya/evolution_surya-ota-sq3a.220705.004-08150846-unsigned.zip.txt
Signed-off-by: Lostark13 <tushar9915@gmail.com>
=> Surya: 08/15/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-sq3a.220705.004-08181549.zip.txt
=> Alioth: 08/19/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220705.004-08201023.zip.txt
=> Vayu: 08/20/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-tp1a.220624.021.a1-08261445-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-tp1a.220624.021.a1-08261750-unsigned.zip.txt, changelogs/starlte/evolution_starlte-ota-tp1a.220624.021.a1-08262241-unsigned.zip.txt
=> Starlte/Star2lte/Crownlte: 08/27/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-sq3a.220705.004-08271011-unsigned.zip.txt
=> Polaris: 20220827 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tp1a.220624.021.a1-08271216.zip.txt
=> Phoenix: 08/27/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-sq3a.220705.004-08301012.zip.txt
=> Vayu: 08/30/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-tp1a.220624.021.a1-09011710.zip.txt
=> Alioth: 09/01/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tp1a.220905.004-09070950.zip.txt
=> Phoenix: 09/07/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-tp1a.220905.004-09072036.zip.txt
=> Alioth: 09/07/2022 Update

builds/spes.json, changelogs/spes/evolution_spes-ota-tp1a.220905.004-09091811-unsigned.zip.txt
Signed-off-by: Hoang Pham Anh Duy <duy@etylix.me>
=> Spes: 09/09/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tp1a.220905.004-09101003.zip.txt
=> Vayu: 09/10/2022 Update

builds/spes.json, changelogs/spes/evolution_spes-ota-tp1a.220905.004-09101345-unsigned.zip.txt
Signed-off-by: Hoang Pham Anh Duy <duy@etylix.me>
=> Spes: 10/09/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-tp1a.220905.004.a2-09191406.zip.txt
=> Alioth: 09/19/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tp1a.220905.004.a2-09201519.zip.txt
=> Vayu: 09/20/2022 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-tp1a.220905.004.a2-09250722.zip.txt
=> Laurel_Sprout: 09/25/2022 Update

builds/veux.json, changelogs/veux/evolution_veux-ota-tp1a.220905.004.a2-09250442-unsigned.zip.txt, devices.json
Signed-off-by: JaswalAshish48 <jaswalashish48@gmail.com>
=> Devices: Add Redmi note 11 Pro plus (veux)

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tp1a.220905.004.a2-09291412.zip.txt
=> Phoenix: 09/29/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tp1a.220905.004.a2-09301142.zip.txt
=> Vayu: 09/30/2022 Update

builds/spes.json, changelogs/spes/evolution_spes-ota-tp1a.220905.004.a2-10011234-unsigned.zip.txt
Signed-off-by: Hoang Pham Anh Duy <duy@etylix.me>
=> Spes: 10/01/2022 Update

builds/spes.json, changelogs/spes/evolution_spes-ota-tp1a.221005.002-10040632-unsigned.zip.txt
Signed-off-by: Hoang Pham Anh Duy <duy@etylix.me>
=> Spes: 10/04/2022 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-tp1a.221005.003-10050532.zip.txt
=> Laurel_Sprout: 10/05/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tp1a.221005.003-10101113.zip.txt
=> Vayu: 10/10/2022 Update

builds/crownlte.json, builds/star2lte.json, builds/starlte.json, changelogs/crownlte/evolution_crownlte-ota-tp1a.221005.003-10141049-unsigned.zip.txt, changelogs/star2lte/evolution_star2lte-ota-tp1a.221005.003-10141306-unsigned.zip.txt, changelogs/starlte/evolution_starlte-ota-tp1a.221005.003-10141412-unsigned.zip.txt
Signed-off-by: Phạm Nguyễn Gia Khiêm <phamnguyengiakhiem@gmail.com>
=> Starlte/Star2lte/Crownlte: 10/14/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-td1a.220804.031-10161604.zip.txt
=> Phoenix: 10/16/2022 Update

builds/munch.json, changelogs/munch/evolution_munch-ota-td1a.220804.031-10182108-unsigned.zip.txt
Signed-off-by: akash07k <akash.galaxy07@gmail.com>
=> Munch: 10/18/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-td1a.220804.031-10200903.zip.txt
=> Vayu: 10/20/2022 Update

builds/alioth.json, changelogs/evolution_alioth-ota-td1a.220804.031-10201429.zip.txt
=> Alioth: 10/20/2022 Update

builds/munch.json, changelogs/munch/evolution_munch-ota-td1a.220804.031-10221919-unsigned.zip.txt
Signed-off-by: akash07k <akash.galaxy07@gmail.com>
=> Munch: 10/22/2022 Update

builds/munch.json, changelogs/munch/evolution_munch-ota-td1a.220804.031-10250104-unsigned.zip.txt
Signed-off-by: akash07k <akash.galaxy07@gmail.com>
=> Munch: 10/25/2022 Update

builds/veux.json, changelogs/veux/evolution_veux-ota-td1a.220804.031-10260715-unsigned.zip.txt
Signed-off-by: JaswalAshish48 <jaswalashish48@gmail.com>
=> veux: 10/26/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-td1a.220804.031-10301108.zip.txt
=> Vayu: 10/30/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-td1a.220804.031-11021854.zip.txt
=> Alioth: 11/03/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-td1a.221105.001-11110408.zip.txt
=> Vayu: 11/11/2022 Update

builds/dipper.json, changelogs/dipper/evolution_dipper-ota-td1a.221105.001-11181320-unsigned.zip.txt
Signed-off-by: Matheus Costa <unreadmatheus@gmail.com>
=> Dipper: 11/18/22 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-td1a.221105.001-12011418.zip.txt
=> Vayu: 12/01/2022 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tq1a.221205.011-12151800.zip.txt
=> Vayu: 12/15/2022 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tq1a.221205.011-12150554.zip.txt
=> Phoenix: 12/15/2022 Update

builds/veux.json, changelogs/veux/evolution_veux-ota-tq1a.221205.011-12190905-unsigned.zip.txt
=> veux: 12/19/2022 Update

builds/polaris.json, changelogs/polaris/evolution_polaris-ota-tq1a.221205.011-12241023-unsigned.zip.txt
=> Polaris: 12/25/2022 Update

builds/mido.json, changelogs/mido/evolution_mido-ota-tq1a.221205.011-12301646-unsigned.txt, devices.json
Signed-off-by: NRanjan-17 <nalinishranjan05@gmail.com>
=> [EvolutionX-CI]: Devices: Add Xiaomi Redmi Note 4/4X (mido)

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tq1a.221205.011-12311102.zip.txt
=> Vayu: 12/31/2022 Update

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-tq1a.221205.011-12311827.zip.txt
=> Alioth: 12/31/2022 Update

builds/mido.json, changelogs/mido/evolution_mido-ota-tq1a.221205.011-01021748-unsigned.zip.txt
Signed-off-by: NRanjan-17 <nalinishranjan05@gmail.com>
=> [EvolutionX-CI]: mido: 01/02/2023 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tq1a.230105.001.a2-01041543.zip.txt
=> Phoenix: 01/05/2023 Update

builds/mido.json, changelogs/mido/evolution_mido-ota-tq1a.230105.001.a2-01050039-unsigned.zip.txt
Signed-off-by: NRanjan-17 <nalinishranjan05@gmail.com>
=> [EvolutionX-CI]: mido: 01/05/2023 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-tq1a.230105.001.a2-01081051.zip.txt
=> Laurel_Sprout: 01/07/2023 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-tq1a.230105.001.a2-01091441.zip.txt
=> Laurel_Sprout: 01/10/2023 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tq1a.230105.001.a2-01101003.zip.txt
=> Vayu: 01/10/2023 Update

builds/laurel_sprout.json, changelogs/laurel_sprout/evolution_laurel_sprout-ota-tq1a.230105.001.a2-01110323.zip.txt
=> Laurel_Sprout: 01/11/23 Update

builds/phoenix.json, changelogs/phoenix/evolution_phoenix-ota-tq1a.230105.001.a2-01170828.zip.txt
=> Phoenix: 01/17/2023 Update

builds/vayu.json, changelogs/vayu/evolution_vayu-ota-tq1a.230105.001.a2-01202200.zip.txt
=> Vayu: 01/20/2023 Update

builds/X01BD.json, changelogs/X01BD/evolution_x01bd-ota-tq1a.230105.001.a2-01231812-unsigned.zip.txt, devices.json
Change-Id: I796ba0a1ddcaa02c9f347a1cc157bd62169369a1
Signed-off-by: Sonal Singh <sonal.singh.19993@gmail.com>
=> X01BD: Initial Release

builds/alioth.json, changelogs/alioth/evolution_alioth-ota-tq1a.230105.001.a2-01271930.zip.txt
=> Alioth: 01/27/2023 Update

builds/veux.json, changelogs/veux/evolution_veux-ota-tq1a.230105.001.a2-01291041-unsigned.zip.txt
=> veux: 01/29/2023 Update

builds/rosemary.json, changelogs/rosemary/evolution_rosemary-ota-tq1a.230105.001.a2-02011152-unsigned.zip.txt, devices.json
Signed-off-by: Beru Hinode <windowz414@1337.lgbt>
=> [Evolution-X CI]: Devices: Add Redmi Note 10S (rosemary)

builds/rosemary.json, changelogs/rosemary/evolution_rosemary-ota-tq1a.230205.002-02071314-unsigned.zip.txt
Signed-off-by: Beru Hinode <windowz414@1337.lgbt>
=> Rosemary: 02/07/2023 Update

builds/veux.json, changelogs/veux/evolution_veux-ota-tq1a.230205.002-02081514-unsigned.zip.txt
=> veux: 02/08/2023 Update

builds/X01BD.json, changelogs/X01BD/evolution_x01bd-ota-tq1a.230205.002-02091026-unsigned.zip.txt
Change-Id: If36220ae69b38909580c48201317f8a7f27e5310
Signed-off-by: Sonal Singh <sonal.singh.19993@gmail.com>
=> X01BD: 02/09/2023 Update

builds/mido.json, changelogs/mido/evolution_mido-ota-tq1a.230205.002-02091229-unsigned.zip.txt
Signed-off-by: NRanjan-17 <nalinishranjan05@gmail.com>
=> mido: 01/11/2023 Update

builds/veux.json, evolution_veux-ota-tq1a.230205.002-02120722-unsigned.zip.txt
=> veux: 02/12/2023 (Safetynet fix) Update

builds/denniz.json, changelogs/denniz/evolution_denniz-ota-tq2a.230305.008.c1-04010951-unsigned.zip.txt, devices.json
I've planning to ship it officially.
=> Devices: Add OnePlus Nord 2 (denniz)

builds/rosemary.json, changelogs/rosemary/evolution_rosemary-ota-tq2a.230405.003.e1-04151951-unsigned.zip.txt, devices.json
* Also remove RN11SE and POCO M5s from device listing.
=> Rosemary: 04/16/2023 Update

builds/onclite.json, changelogs/onclite/evolution_onclite-ota-tq3a.230605.012-06250611-unsigned.zip.txt, devices.json
=> onclite: 06/25/2023 Update

builds/lemonade.json, builds/lemonadep.json, changelogs/lemonade/evolution_lemonade-ota-tq3c.230805.001.b2-08101325-unsigned.zip.txt, changelogs/lemonadep/evolution_lemonadep-ota-tq3c.230805.001.b2-08101317-unsigned.zip.txt
Signed-off-by: imminentgit <imminentgit@gmail.com>
=> Lemonade/p: 08/10/2023 Update

builds/lemonade.json, builds/lemonadep.json, changelogs/lemonade/evolution_lemonade-ota-tq3c.230805.001.b2-08161057-unsigned.zip.txt, changelogs/lemonadep/evolution_lemonadep-ota-tq3c.230805.001.b2-08161131-unsigned.zip.txt
Signed-off-by: imminentgit <imminentgit@gmail.com>
=> Lemonade/p: 08/16/2023 Update

builds/lemonade.json, builds/lemonadep.json, changelogs/lemonade/evolution_lemonade-ota-tq3c.230901.001.b1-09231341-unsigned.zip.txt, changelogs/lemonadep/evolution_lemonadep-ota-tq3c.230901.001.b1-09231330-unsigned.zip.txt
Signed-off-by: imminentgit <imminentgit@gmail.com>
=> Lemonade/p: 09/23/2023 Update

builds/lunaa.json, changelogs/lunaa/evolution_lunaa-ota-tq3c.230901.001.b1-09241842-unsigned.zip.txt
=> Lunaa: 09/28/2023 Update

generate_device_groups.sh
=> generate_device_groups: Use fzf for choosing the editor

builds/stone.json, changelogs/stone/evolution_stone-ota-uq1a.231205.015-12160754-OFFICIAL.zip.txt
please accept it, as update need to push
=> stone: 17/12/2023 Update

builds/PL2.json, changelogs/PL2/evolution_PL2-ota-uq1a.240205.004-02271854-OFFICIAL.zip.txt, devices.json
Signed-off-by: Akshat <Legendleo90@users.noreply.github.com>
=> PL2: 02/27/2024 Update

builds/topaz.json, changelogs/topaz/evolution_topaz-ota-uq1a.240205.004-03072309-OFFICIAL.zip.txt, devices.json
* updated my displayed name
* Add topaz
=> Topaz: 03/08/24 Update

builds/PL2.json, changelogs/PL2/evolution_PL2-ota-ap1a.240405.002-04182310-OFFICIAL.zip.txt
Signed-off-by: Akshat <Legendleo90@users.noreply.github.com>
=> PL2: 04/18/2024 Update
